# Generated by Django 4.2.5 on 2023-10-15 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0002_rename_authoruser_author_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='User',
            new_name='authorUser',
        ),
    ]
