# Generated by Django 4.2.5 on 2023-10-21 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0003_rename_user_author_authoruser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='ratingAuthor',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='authorUser',
            new_name='User',
        ),
    ]
