# Generated by Django 4.2.5 on 2023-10-21 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0004_rename_ratingauthor_author_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='User',
            new_name='AuthorUser',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='Author',
            new_name='ratingAuthor',
        ),
    ]
